/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * Declaration flags — questions raised by a candidate's own Form 26 filing.
 *
 * These are leads, not findings, and the UI is required to say so. Each flag
 * carries the figures it was derived from, the assumption behind it, and the
 * ordinary innocent explanation, so a reader can weigh it rather than take it
 * on trust. Nothing here asserts wrongdoing and nothing here names an offence.
 *
 * Generated by scripts/buildDeclarationFlags.cjs, whose header records what
 * this replaced and why.
 */

export interface FlagEvidence {
  label: string;
  value: string;
}

export interface DeclarationFlag {
  code: string;
  title: string;
  detail: string;
  evidence: FlagEvidence[];
  /** The declared text the flag came from, quoted verbatim where there is one. */
  asFiled?: string;
  /** The threshold or premise this check rests on, always shown to the reader. */
  assumption: string;
  /** The ordinary, innocent reading of the same figures. */
  alsoExplainedBy: string;
}

interface FlagFile {
  generatedAt: string;
  source: string;
  candidatesExamined: number;
  candidatesFlagged: number;
  flags: Record<string, DeclarationFlag[]>;
}

let filePromise: Promise<FlagFile | null> | null = null;

function load(): Promise<FlagFile | null> {
  if (!filePromise) {
    filePromise = fetch('/data/declaration_flags.json')
      .then(r => (r.ok ? r.json() : null))
      .catch(() => null);
  }
  return filePromise;
}

/** Flags for one candidate. Empty for the great majority, which is the point. */
export async function loadDeclarationFlags(candidateId: string): Promise<DeclarationFlag[]> {
  const file = await load();
  return file?.flags[candidateId] ?? [];
}

/** Provenance for the note shown under the flags. */
export async function loadFlagProvenance(): Promise<Pick<FlagFile, 'generatedAt' | 'candidatesExamined' | 'candidatesFlagged'> | null> {
  const file = await load();
  if (!file) return null;
  const { generatedAt, candidatesExamined, candidatesFlagged } = file;
  return { generatedAt, candidatesExamined, candidatesFlagged };
}
